/* Generated By:JavaCC: Do not edit this line. CParserDSDLConstants.java */
package scenarios.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CParserDSDLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENTARY = 2;
  /** RegularExpression Id. */
  int EOL = 3;
  /** RegularExpression Id. */
  int ACC_OPEN = 4;
  /** RegularExpression Id. */
  int ACC_CLOSE = 5;
  /** RegularExpression Id. */
  int PAR_OPEN = 6;
  /** RegularExpression Id. */
  int PAR_CLOSE = 7;
  /** RegularExpression Id. */
  int SEP = 8;
  /** RegularExpression Id. */
  int ASSOCIATE = 9;
  /** RegularExpression Id. */
  int AT = 10;
  /** RegularExpression Id. */
  int DO = 11;
  /** RegularExpression Id. */
  int DAY = 12;
  /** RegularExpression Id. */
  int DURING = 13;
  /** RegularExpression Id. */
  int EACH = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int EVERYDAY = 16;
  /** RegularExpression Id. */
  int EXCEPT = 17;
  /** RegularExpression Id. */
  int FOR = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int OF = 20;
  /** RegularExpression Id. */
  int ON = 21;
  /** RegularExpression Id. */
  int SWITCH_OFF = 22;
  /** RegularExpression Id. */
  int SWITCH_ON = 23;
  /** RegularExpression Id. */
  int THEN = 24;
  /** RegularExpression Id. */
  int TO = 25;
  /** RegularExpression Id. */
  int WAIT = 26;
  /** RegularExpression Id. */
  int WHEN = 27;
  /** RegularExpression Id. */
  int DAYS = 28;
  /** RegularExpression Id. */
  int UNIT = 29;
  /** RegularExpression Id. */
  int DATE = 30;
  /** RegularExpression Id. */
  int TIME = 31;
  /** RegularExpression Id. */
  int U_SECONDS = 32;
  /** RegularExpression Id. */
  int U_MINUTES = 33;
  /** RegularExpression Id. */
  int U_HOURS = 34;
  /** RegularExpression Id. */
  int U_DAYS = 35;
  /** RegularExpression Id. */
  int ID = 36;
  /** RegularExpression Id. */
  int NUMBER = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<COMMENTARY>",
    "<EOL>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"associer\"",
    "\"a\"",
    "\"faire\"",
    "\"jour\"",
    "\"pendant\"",
    "\"chaque\"",
    "\"autre\"",
    "\"chaque jours\"",
    "\"sauf\"",
    "\"pour\"",
    "\"si\"",
    "\"de\"",
    "\"sur\"",
    "\"eteindre\"",
    "\"allumer\"",
    "\"puis\"",
    "\"vers\"",
    "\"attendre\"",
    "\"quand\"",
    "<DAYS>",
    "<UNIT>",
    "<DATE>",
    "<TIME>",
    "<U_SECONDS>",
    "<U_MINUTES>",
    "<U_HOURS>",
    "<U_DAYS>",
    "<ID>",
    "<NUMBER>",
  };

}
